### ISSUE TITLE
Improve Paginator UI

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#114]
### TODO

- [x] Expand the paginator to fit the width of the internship card list frame (see below image)
- [x] Add a shadow above the paginator
- [x] Change the color of the paginator to maroon

### Notes

![Untitled](https://user-images.githubusercontent.com/78290887/228394011-e0f4707f-eb57-4e68-9114-7259bc19fd88.png)
