### ISSUE TITLE
Create scraping process diagram

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#122]
### Context

The code will get incredibly convoluted if we don't have a central place to document our scraping process. If we want it to scale, use multiple scrapers at a time, and update internships on a regular basis efficiently, we'll need to spell out the steps.

### TODO

- [ ] Create a process diagram for the scraper
- [ ] Share the process diagram over Discord
- [ ] Add this process to the wiki

### Notes

**Comment by johndpjr** [comment]
Will include this in #123
