### ISSUE TITLE
Revamp wiki & documentation

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#123]
### Context

Our wiki needs a good revamp. It is barely filled out and incredibly outdated (it still has `tkinter` stuff!).

### TODO

- [ ] Add more information to the the wiki and clean up the look
- [ ] Cover all parts of the repository, from installation and running to scraping to Angular
- [ ] Create a process diagram for the scraper and add to wiki
- [ ] Share wiki over Discord when finished

### Notes
