### ISSUE TITLE
Create login page

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#127]
### Context

We need to start creating a login page so that we can track internships on a user-by-user level. This ticket _won't_ implement major login functionality.

### TODO

- [x] Route the main job search page to `/jobs` (it is no longer the default route)
- [x] Create a "Login" page for the `/login` route. See **Figure 1** for a mockup
  - [x] Route to the main job search page (`/jobs`) when the "Continue as Guest" button is clicked
  - [x] Route to the "Sign Up" page (`/sign-up`) when the "Sign Up" button on the "Login" page (`/login`) is clicked
- [x] Create a "Sign Up" page for the `sign-up` route. See **Figure 2** for a mockup
- [x] The home page (default route "/") should route to "/login". Check out the [Angular tutorial](https://angular.io/guide/router) for common routing tasks

### Notes

_* There is no need to implement login functionality just yet (that will come later)._

![agtern-login](https://user-images.githubusercontent.com/78290887/232351966-dafe75df-8aaa-4f1b-a2bb-fd55afef8226.png)
**Figure 1. AgTern "Login" page (`/login`) mockup.**

![agtern-create-account](https://user-images.githubusercontent.com/78290887/232351686-c2e708b4-2d64-486e-8ce1-a656e1622d73.png)
**Figure 2. AgTern "Sign Up" page (`/sign-up`) mockup.**
