### ISSUE TITLE
Improve Docker configurations

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#132]
### Context

Docker is a powerful tool that we should take advantage of to simplify running the server and scraper.

### TODO

- [ ] Improve the Docker and environment configurations so that there is a unified way to run the repo
- [ ] Create Docker templates for different purposes (scraping, web server, frontend, backend, etc.)
- [ ] Add Docker local development + update containers

### Notes
