### ISSUE TITLE
Find rotating proxy service

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#145]
## Context

A [rotating proxy](https://smartproxy.com/blog/why-rotating-proxies-are-the-best#:~:text=A%20rotating%20proxy%20is%20a,managing%20multiple%20social%20media%20accounts.) helps us make more web requests by changing our IP after a set time or after a certain number of requests. If we want our web scraper(s) to scale, we need to make requests appear as if multiple users are accessing company job boards, otherwise our IP will be blacklisted and we will not be able to access that site through that IP anymore.

## TODO

- [x] Learn about rotating proxies (see above site)
- [x] Research rotating proxy services and choose one that best suites our need (multiple factors at play here, but focus on _reliability_, _cost_, _volume_, and _speed_). This service should be a reasonably low cost (free is preferable, but no more than $5-20 / month)
- [x] Once a proxy service is chosen, add a comment here and @johndpjr 

## Notes

This proxy service won't yet be used in our project since our web scraping volume is not large, but once we do have a better scraping system in place with multiple web scrapers, this will become necessary. It's good to be prepared with potential options already.

**Comment by saketmugunda123** [comment]
Rotating Proxy: smartproxy $7.50 for 3 IP addresses
Based on what I've researched, there are two viable options for our rotating proxy service. The first one is the most popular smartproxy. It has been awarded the best value rotating proxy and has the numbers to back it up. The average response time for the proxy service is less than 0.6 seconds, an industry best. Further, the success rate of smartproxy is 99.47%, a mark that is also the highest in the market. On top of all that, there is an affordable plan that provides us 3 IP addresses for $7.50 a month. With reliability, smartproxy is viewed as one of the most reliable in the market and doesn't violate any international laws. Unfortunately, cheaper services like PacketStream doesn't allow for custom rotation, and duplicate IP address usually occur. With all of this, smartproxy's 3 IP addresses for $7.50 a month while providing efficient and reliable service makes it the best service for our needs @johndpjr
