### ISSUE TITLE
Modify companies with scraping config

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#146]
## Context

All of our scraping configurations are defined in the `data/companies` folder in JSON files. Each company has its own scraping config (which we have defined [here](https://github.com/johndpjr/AgTern/wiki/Web-Scraping)). Some companies have a `scrape: null` key-value mapping; this means that we have not defined a scraping config for that company's job board yet, but are planning to.

## TODO

- [x] Read the [scraping config definition](https://github.com/johndpjr/AgTern/wiki/Web-Scraping)
- [x] Look at companies that already have a complete scraping config and get a feel for how it works
- [x] Understand the [Document Object Model (DOM)](https://www.w3.org/TR/WD-DOM/introduction.html) and what [XPath](https://www.w3schools.com/xml/xpath_syntax.asp) is
- [x] Look at a specific company configuration, go to the `link` property, open [Chrome dev tools](https://developer.chrome.com/docs/devtools/open/), and use [the Chrome element inspector debugger](https://developer.chrome.com/docs/devtools/dom/) to look at the scraping properties and what is being scraped (i.e. look at the `xpath` property and match it with the web element/text /header that you see on the company job board in your web browser)

## Notes
