### ISSUE TITLE
Validate company scraping configurations

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#149]
## Context

All of our scraping configurations are defined in the `data/companies` folder in JSON files. Each company has its own scraping config (which we have defined [here](https://github.com/johndpjr/AgTern/wiki/Web-Scraping)). However, when we run the program, we need to validate _that the company scraping config is valid **before** scraping begins._ One such data validation library is called [Cerberus](https://docs.python-cerberus.org/index.html), which is lightweight and easily configurable. The idea is that Cerberus will be able to validate the syntax/structure of the scraping config JSON so that we are guaranteed to be running a valid scrape (see their [usage docs](https://docs.python-cerberus.org/usage.html) for more info on how it works).

## TODO

- [x] Read the [scraping config definition](https://github.com/johndpjr/AgTern/wiki/Web-Scraping)
- [x] Look at companies that already have a complete scraping config and get a feel for how it works
- [x] Install and add Cerberus as a dependency by adding `Cerberus==1.3.5` to the `requirements.txt` file and run `pip3 install -r requirements.txt`
- [x] Before the scraping begins, it will be known what companies are slated to be scraped; you will need to create a function / class for validating these scraping configurations _for each company that will be scraped._ This is as easy as running the Cerberus validator on each of the JSON files that will be scraped (see this [guide](https://www.freecodecamp.org/news/python-read-json-file-how-to-load-json-from-a-file-and-parse-dumps/) on how to read JSON as dict)
- [x] If a scraping configuration is invalid for a given company, log the error, skip that company, _and continue scraping (obviously excluding the invalid company scraping config)._

## Notes

_Some companies have a `scrape: null` key-value mapping; this means that we have not defined a scraping config for that company's job board yet, but are planning to. The validator should allow this._
