### ISSUE TITLE
Configure Sphinx documentation generator

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#150]
## Context

Our documentation is inconsistent in style and form - and spotty in some places. Important functions need proper documentation. To work towards this, we would need a standardized documentation format. [Sphinx](https://www.sphinx-doc.org/en/master/) is a documentation generator. This documentation will eventually include everything about the project: overview, installation instructions, contributing, and code documentation. This ticket will just set Sphinx up.

## TODO

- [x] Add and install Sphinx as a dependency by adding `Sphinx==7.2.6` to the `requirements.txt` file and run `pip3 install -r requirements.txt`
- [x] Follow Sphinx [documentation tutorial](https://www.sphinx-doc.org/en/master/usage/quickstart.html)
- [x] Configure and integrate Sphinx with the repository according to the quickstart above and the Sphinx documentation

## Notes

_This story is only beginning the auto-documentation process. You don't need to convert all the functions we currently have to the Sphinx format, but please do try at least a few and then running the tool on them to ensure that it works._

**Comment by johndpjr** [comment]
Able to generate `docs` now!
