### ISSUE TITLE
Add logo and clickable banner to toolbar

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#163]
## Context

Our banner in the top left corner of the screen doesn't do much - all it contains is the text "AgTern" - without any interaction. Let's change that.

## TODO

- [x] Add the AgTern logo (attached in Figure 2) and a vertical white line to the top left banner (see Figure 1)
- [x] Make the rectangular section that contains the logo, white line, and AgTern text clickable
- [x] Route the user to the home page when the banner is clicked

## Notes

![banner](https://github.com/johndpjr/AgTern/assets/78290887/3ad95189-9505-4448-ad5d-33a7975bdec6)
**Figure 1. Banner mock-up.**

![favicon](https://github.com/johndpjr/AgTern/assets/78290887/d6d3c601-8e4c-4938-9c0e-c4ea773b9219)

**Comment by johndpjr** [comment]
Banner added!
