### ISSUE TITLE
Implement OAuth on backend

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#169]
## Context

Nearly all the backend setup can be complete on its own. Use a provider like [OAuthlib](https://oauthlib.readthedocs.io/en/latest/index.html). Once #168 is complete, you can use its provided OAuth and credential data to fully implement the backend

## TODO

- [x] Create or modify backend endpoints to support OAuth login and sign up
- [x] Persist OAuth sessions and user data in a database
- [x] Support logging and signing up through Google

## Notes

**Comment by Jwdegames** [comment]
We technically already have the first part implemented.

**Comment by Jwdegames** [comment]
For logging in and signing up through google, we should follow these steps:
https://developers.google.com/identity/sign-in/web/sign-in
https://developers.google.com/identity/sign-in/web/backend-auth
- We probably need to store extra info in the user model - the google ID token (we should not store the actual ID in our database), and whether or not the user has created a password. Then, the login system should be updated to only allow logins from our login system when the user has created a password. Otherwise, they can login in via Google.

**Comment by Jwdegames** [comment]
Note: The login endpoints need to be modified to accept login via google. Probably a new function is needed for loggin in via google.
