### ISSUE TITLE
Spin up new droplet on DigitalOcean

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#175]
## Context

Our droplet on DigitalOcean will be non-functioning after 11/8, so we'll need to spin up another one from another account.

## TODO

- [x] Create an account and use the GitHub student pack to get $200 of DigitalOcean credit
- [x] Spin up a new droplet (and document the process on how to do so)
- [ ] Make the newest version of AgTern accessible through the droplet
- [x] Change tx.ag/tern location to new droplet IP address

## Notes

**Comment by johndpjr** [comment]
Will consider setting up my own home server
