### ISSUE TITLE
Populate internship list items with functional buttons

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#20]
Before we begin web scraping and displaying the internships, it's a good to get a general idea of the flow of our program. When we scrape internships, we will be populating the `InternshipListFrame` with internship items that correspond to what we scrape. When you click on one of these items, the details appear in the `InternshipDetailFrame`.

### TODO

- [x] Create at least 5 internships (found already) of varying characteristics (grad. year, description, period, etc.)
- [x] When the `InternshipListFrame` is initialized, for each of the internships above, create a button that has the text `COMPANY\nTITLE\nPERIOD/YEAR`
- [x] When clicked, display the internship details of the corresponding internship in the `InternshipDetailFrame` using the `Internship` model (in `agtern/models`)

### Notes

Since this doesn't involve scraping, we won't be using these internships again, but it's helpful to at least get something concrete down.
