### ISSUE TITLE
Improve internship details styling

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#22]
### Context
We all know that the `InternshipDetailFrame` looks ugly- let's change that.
![agtern-internship-details](https://user-images.githubusercontent.com/78290887/192793760-eb2d7647-7db7-450d-91e0-ac8b820df26c.png)

### TODO

- [ ] Make "Internship details" bold and larger
- [ ] Make the font size for all internship details larger (company, title, etc.)
- [ ] Add the attached icon to the project in the `agtern/gui/assets` folder and place it into the "Apply now" button (see the `InternshipListFrame` search box for inspiration on how to do this)

### Notes
Use this icon for the 3rd TODO:
![external-link](https://user-images.githubusercontent.com/78290887/192795493-93013599-676e-4360-b100-8798298b1ce5.png)
