### ISSUE TITLE
Scrape Tesla links

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#33]
### Context
We need a way to get the links from Tesla so that the user does not need to find the links themselves.

### TODO

- [x] Get the `href` attribute from each `a` tag, **but still maintain** all other element text attributes (like `company`, `title`, etc.)
- [x] Add a `link` key in the `scrape` section for Tesla in `scraping_config.json`
- [x] Write each link to the database, like all other attrs.
