### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#36]
### Context

The README contains a lot of out-of-date information. Let's add some more information so that contributors and outsiders can understand AgTern more thoroughly.

### TODO

- [x] Update the introductory paragraph to be more engaging and descriptive
- [ ] Update the features to match what can currently be done (and include future/planned features)
- [x] Provide hyperlinks to other places (like wiki, documentation, contributing, etc.)
- [x] Reformat and update "Python Packages Used" section to reflect current software uses
