### ISSUE TITLE
Integrate internship scraping with GUI pipeline

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#37]
### Context

We've created an API and configuration format for scraping internships and writing them to disk (as a csv file). We now need to read these internships from the disk and populate the GUI with internship list item buttons so that a user can click on a button, find out more information about the internship, and click the "Apply now" button to open a tab in their browser that goes to the corresponding internship apply link. This all should happen within a tightly coupled API that makes our pipeline and process clear.

### TODO

- [ ] Create a parsing step after scraping that extracts `year` and `period` from the internship title (it's fine if certain information cannot be extracted from _every_ title)
- [x] Modify `get_all_internships` so that it returns a list of `Internship` objects
- [x] When the `InternshipListFrame` is initialized, populate it with internship buttons from `get_all_internships` (this will still have the behavior of previous internship buttons - this just uses real-world data)

### Notes

This is the last ticket that fully implements the Minimum Viable Product (MVP). Expect that the API for retrieving Internships **will** be changed and that the scraping will eventually be moved to a central server that our client will contact.
