### ISSUE TITLE
Add search frame to GUI

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#46]
### Context

Our GUI is lacking. It has limited functionality, poor window resizing, and is not very user-friendly/descriptive.

We need to improve the look and feel of the application so that users can have an experience that is easy to use, looks good, and makes sense. To accomplish this goal, we should add a fully-fledged filter and search frame to make the internship search more relevant and specific to each user. Finally, we should change the layout, name, and style of widgets that need to be more descriptive and/or look better.

### TODO

- [x] Create an `InternshipSearchFrame` and place it in the far left application frame
- [x] Place filtering widgets in the `InternshipSearchFrame` as shown in the mockup attached below
- [x] Set a larger default window size
- [ ] Make all 3 main application frames (`InternshipSearchFrame`, `InternshipListFrame`, and `InternshipDetailFrame`) proportional and uniform in size (i.e. when the window is resized, make sure the frames resize proportionally)
- [ ] Look into ttk widgets (like `ttk.Button` instead of `tk.Button`) and/or ttk themes that make our widgets look better/more consistent
- [ ] Make any changes necessary to ensure that the application can look as good as tkinter allows

### Notes

Wait until project restructuring is done (another issue). _Don't add functionality to the "Search", "Filter", or "Sort by" buttons; this will be done later._

![image0](https://user-images.githubusercontent.com/78290887/197369614-a76a8259-d8dd-4b86-9a26-540bac8aee65.png)
_Figure 1: @stevenmao27 mockup_

---

![InternshipSearchFrame mockup](https://user-images.githubusercontent.com/78290887/197363835-af5c5a17-b90e-4d25-815f-8fbc982815de.jpg)
_Figure 2: Project meeting mockup_
