### ISSUE TITLE
Cloud solutions & providers

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#47]
### Context

Since we are moving to a client-server architecture, we will eventually need to host our server on the cloud. We can do this through cloud solutions providers like AWS, GCP, or Azure.

### TODO

- [x] Find a cloud provider that meets the needs of our project and is cost-efficient, reliable, and easy-to-use
- [x] Make a comment below with your findings and analysis of _all reasonable_ options available and _explain_ why you've selected this one provider over the others another
- [x] Additionally, provide some pros and cons of this provider in the report

### Notes

I've assigned this to @gitRawry , but this is a discussion- I encourage everyone else to find and discuss providers and solutions that they've researched as well. Also, make sure to give feedback on solutions that are offered and if it's the best fit for our project!

**Comment by gitRawry** [comment]
10/29/2022
https://docs.google.com/presentation/d/1yHp6qDa8Nce6VoHe-ywXve3clFm2CMdMJPifitdE_Uk/edit?usp=sharing

- Agreed on AWS
- Talked about possible digitalocean use, as it is cheaper and simpler

**Comment by johndpjr** [comment]
This past meeting, we have decided on DigitalOcean as the provider, as we think it is better cost-wise and simpler to get started. Looks like $200 of credit for first 12 months (a "droplet" instance is only $4/month). @brendanehrman1 is working on this

**Comment by johndpjr** [comment]
A DigitalOcean instance is active now. Brendan added everyone who's actively contributing/attending meetings. Future concerns with DigitalOcean should be opened in another issue
