### ISSUE TITLE
Implement "My Profile" button

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#5]
### TODO

- [ ] When the "My Profile" button is clicked, open the Preferences TopLevel widget from #6 
- [ ] Every button has a `command` attribute which is a function that runs when the button is clicked; use the `_on_my_profile_bttn_click` function in `TopBarFrame` to open this TopLevel widget
- [ ] Remove the debug print statement in the previous function
- [ ] Add a more descriptive docstring

### Notes
The functionality of the Preferences window should already be implemented per #6, so no further things need to add unless a bug was introduced.
