### ISSUE TITLE
Set up client-server architecture

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#50]
### Context

With the move to the client-server model, we will need to make a web server, create an API (that the GUI will use), and set up a database. The database is used to store all of the scraping data and will do the scraping actions. The client GUI is in `agtern/gui` and the server code resides in `agtern/server`. All shared scripts between the client and the server are stored in `agtern/common`.

### TODO

- [x] Use the web framework [FastAPI](https://fastapi.tiangolo.com/) to create a server to handle all API requests. It should be put in `agtern/server`
- [ ] Set up a database in `agtern/server/database` and integrate it with the API
- [x] Create a database `Internship` model that can be used by the database, API, and the GUI application (or two models if not possible- try to keep the old `Internship` `dataclass` model)
- [ ] Add `fastapi` and all other dependencies to `requirements.txt`
- [ ] Create some build and run scripts for the new developer and client workflow

### Notes

This is a big ticket. I'll try and finish it by next meeting (10/29/22) so that we can refactor and expand it.
