### ISSUE TITLE
GUI filtering improvements

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#59]
### Context

We have a much better looking GUI due to #46 being completed. A few small things were overlooked, however. To make our GUI more consistent, we should add some improvements.

### TODO

- [ ] Make the "Sort by" drop-down optionmenu the same theme as the rest of the optionmenus (it still has the old theme)
- [ ] Hovering over internship buttons causes noticeable flashing when entering and exiting the button frame: find ways to change the hovering background colors of the internship buttons all at once to reduce the flashing
- [ ] Implement the search box (#29)
- [ ] Auto-fill the filter OptionMenus with what's currently in the Configuration file (i.e. if "Computer Science and Engineering" is set for "Major" in the config file, then auto-fill that in the OptionMenu so the user doesn't have to click on it). If there is not a corresponding value for a configuration item ("Major", "Graduation Year", etc.), then use a default value that is reasonable.

**Comment by johndpjr** [comment]
Our project is migrating to Angular; tkinter is not relevant anymore. I'll create a new ticket once we know more information about the Angular dev environment.
