### ISSUE TITLE
Ask for student profile on *first* load

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#6]
### TODO
- [x] Check the configuration file and see if anything has been written to yet (i.e. the `name` field (or any other one) is populated) - if it is populated, you know a profile is already been made
- [x] If a profile has **not** been made, open a [TopLevel](https://www.pythontutorial.net/tkinter/tkinter-toplevel/) window **without** starting the main `Application` and display some kind of preferences UI that allows the user to read/write all values of the `config.ini` file created earlier
- [x] When the user clicks "Save", validate the data and write the new configuration to the `config.ini` file (you'll have to use ConfigParser in all cases, of course)

### Notes
I've attached a mockup of this preferences page, but you have total creative freedom to do something different if you want. Remember this is the minimum viable product.

_You might also want to research additional widgets like Entry which allow you to preselect values and thus not need validation._

[mockup.pdf](https://github.com/johndpjr/AgTern/files/9639898/2022-09-24.21-37.pdf)

**Comment by johndpjr** [comment]
### TODO
- [ ] Check the configuration file and see if anything has been written to yet (i.e. the `name` field (or any other one) is populated) - if it is populated, you know a profile is already been made
- [ ] If a profile has **not** been made, open a [TopLevel](https://www.pythontutorial.net/tkinter/tkinter-toplevel/) window **without** starting the main `Application` and display some kind of preferences UI that allows the user to read/write all values of the `config.ini` file created earlier
- [ ] When the user clicks "Save", validate the data and write the new configuration to the `config.ini` file (you'll have to use ConfigParser in all cases, of course)

### Notes
I've attached a mockup of this preferences page, but you have total creative freedom to do something different if you want. Remember this is the minimum viable product.

_You might also want to research additional widgets like Entry which allow you to preselect values and thus not need validation._



[2022-09-24 21-37.pdf](https://github.com/johndpjr/AgTern/files/9639898/2022-09-24.21-37.pdf)
