### ISSUE TITLE
Set up Droplet instance on DigitalOcean

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#69]
### Context

We have decided on DigitalOcean as our cloud provider. GitHub offers a student pack with free $200 credit for DigitalOcean for 12 months. Keeping one instance up is only $4/month. We should set up a droplet instance, but **we shouldn't** to make the API public or run anything on it _yet_ since we still have much to do to secure the program. 

### TODO

- [x] Create a DigitalOcean account with GitHub student pack $200 credit
- [x] Spin up a "Droplet" instance
- [x] Give _active_ team members access to this instance

### Notes

**Comment by johndpjr** [comment]
A DigitalOcean instance is active now. Brendan added everyone who's actively contributing/attending meetings. Future concerns with DigitalOcean should be opened in another issue
