### ISSUE TITLE
Extract tags from description

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#70]
### Context

Since the cornerstone of AgTern is its ability to filter internships, the best way we can do this is extract keywords from the description as tags and match tags against the student's major's tags. For example if "software" shows up in an internship description, it will match to one of Computer Science's pre-defined tag "software" and thus match the internship to the student. 

### TODO

- [ ] Extract keywords from the internship description that _relate and identify_ it from other internships (pick up on unique keywords like "C++", "Python" or "software")
- [ ] Add these tags to the database for that internship as we scrape
- [ ] Add pre-defined tags to the `Majors` table in the database for each major

### Notes

**Comment by johndpjr** [comment]
Closing because we aren't matching up majors, but we are simply generating keywords
