### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#76]
### Context

Considering the move to Angular, it should be necessary to change the structure of the project quite a bit, just like in the client-server move. Now, the Angular frontend is separated from the FastAPI/scraping backend

### TODO

- [ ] Create a `backend` and `frontend` folder
- [ ] Remove `common` and `gui`
- [ ] Change run configurations in Pycharm

### Notes
