### ISSUE TITLE
Create web scraping algorithm

### ISSUE THREAD

**Issue by JeremyEastham** [johndpjr/AgTern#8]
# To-Do
- [x] Read websites from CSV file (#4)
- [x] Use Selenium to extract internship information off of those websites
- [x] Save the extracted information into the Internship model (#7)
- [x] Provide a function or API to retrieve that data (used by frontend)
- [x] Save/cache the internships into a file or database

### Later:
- [ ] Use profile information to scrape only relevant internships?
- [ ] Filter internships using profile information (input to function or API when retrieving data)

### Important:
- [x] Ensure separation of concerns between the backend web scraper and the frontend GUI so that we can use something other than TKinter for our final product
