### ISSUE TITLE
Add basic functionality to frontend

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#82]
### Context

Now that the template for the Angular frontend is created, we need to add basic functionality to it. The frontend should populate ~50 internships from the database using the `AgTernAPI` service. Read more about Angular services [here](https://angular.io/guide/architecture-services)

### TODO

- [x] Use the `AgTernAPI` service to populate the internship list component with internship components (custom buttons)
- [x] When an internship button is clicked, populate the title, apply now button, and description in the internship detail component
- [x] When the "Apply now" button is clicked, open a new tab with the corresponding link

### Notes

Just display ~50 internships for now. This can be done by passing a limit parameter into the `AgTernAPI` call.
