### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#84]
### Context

Now that the project's frontend has changed and we've accomplished and modified more tasks relating to the roadmap, we should update the README.

### TODO

- [ ] Update
- [ ] Remove tkinter GUI image from `Images` section and add one image of the Angular GUI in action (something similar to the tkinter image- make sure the image includes the internship detail frame populated with an internship)
- [ ] Remove yellow tkinter image in the `Built With` section and replace it with the red Angular image (it should be commented below the tkinter image)
- [ ] Update run configurations in the `Running` section are up-to-date with the frontend move
- [ ] Mark any completed tasks in the `Roadmap` section and change the "Move the server to AWS EC2 instance" task to "Move the server to Digital Ocean droplet instance" and mark it as complete
