### ISSUE TITLE
Add Major table to database

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#85]
### Context

Since we are categorizing internships and accessing college majors in a systematic way, we should add a Major table to the database.

### TODO

- [ ] Add a `Major` table to the database. Create a `Major` model in the `backend/app/models` folder with the following fields: `id` (look at `Internship` model for inspiration), `title` (type is String), and `tags` (type is list of Strings)
- [ ] For all majors (Computer Science, Electrical, etc.), create around 15 tags that relate to that major. For example, "software" is a good tag for the Computer Science major. These tags will be used later to categorize internships when we process the text of the description and match tags to the tags in this table
- [ ] When the backend is initialized (run), ensure that all Majors are added with their related tags (_no repeats_)
