### ISSUE TITLE
Setup Docker configurations

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#86]
### Context

In order to create a consistent environment and allow our application to scale a lot better, we should be using tools like [Docker](https://www.docker.com/) in development and when deploying to production. These containers can be spun up and down and can run different parts of the application. For example, we can have a container running the backend API, another the Database, and another the Web server. That way if we want to scale the web server without scaling the backend API, we can do that.

**I've found a really good reference [site](https://www.baeldung.com/ops/multiple-dockerfiles#docker-compose) that explains how to set up these things**

### TODO

- [ ] Create a `docker-compose.yml` in the root of the project and a `docker` folder (this will contain the Dockerfiles)
- [ ] Create `frontend` and `backend` folders in the `docker` folder and add a `Dockerfile` into each of the two directories
- [ ] Modify each `Dockerfile` to run the code for the `frontend` and `backend`, respectively.

### Notes

When all this configuration is complete, we'll be able to create Docker containers on the fly with `docker-compose up` to build and run the containers.

Check out the documentation for Docker (it's really good): https://docs.docker.com/engine/reference/builder/

**Comment by JeremyEastham** [comment]
### Docker Container Setup
1. Install Python & Node.js
2. Run `pip install` at the root
3. Run `npm install` in `frontend`
4. Run `npm build` in `frontend`
5. Run `python -m backend` at the root

We also need to figure out how to persist `/data` and `/log`. I believe Docker has a way to map certain folders in the container to actual folders that are not destroyed when the container is destroyed.

**Comment by nkilm** [comment]
#### I would like to work on this issue.

**Comment by nkilm** [comment]
I'll open individual PR for each modification, this way it'll be more clear and managable.

**Comment by johndpjr** [comment]
@nkilm I'm sorry but development is open to only Texas A&M students. I appreciate your help!

**Comment by nkilm** [comment]
@johndpjr Okay
