### ISSUE TITLE
Improve UI looks

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#90]
### Context

Right now the Angular UI looks a **lot** better than what `tkinter` offered. However, there's still a lot of UI improvements that could be made.

### TODO

- [x] Fix "Apply now" button cutoff (Figure 1). The text "Apply now" and the logo to the right should fit inside the button and not be cut off when the title is longer.
- [ ] Visually show that the internship card is clicked and selected when clicked (Figure 2). Right now, there is no indication that the internship card was clicked and selected. Maybe when it is clicked, show a light maroon color and some kind of card-click animation.
- [x] Make _only_ the `internship-list` component scrollable (Figure 3)- the `internship-details` component shouldn't scroll with it (i.e. make the `internship-details` component "stick" to the right side)

### Notes

![apply-now-bttn-cutoff](https://user-images.githubusercontent.com/78290887/202802218-ced8958c-2024-4895-81c0-af4c4f49548b.jpg)

_Figure 1. Notice that contents of the button are cut off._

---

![internship-card-clicked](https://user-images.githubusercontent.com/78290887/202802607-c686ba93-ea71-491e-8f5e-909cf71e04ff.png)

_Figure 2. The "Public Policy" internship was clicked but the user has no indication that it was clicked or that it is currently selected (other than the hover animation, but that only activates on hover event)._

---

![scrolling](https://user-images.githubusercontent.com/78290887/202803094-ae8edbcd-5621-43df-b349-4075ef053b47.png)

_Figure 3. The internship details scroll as you scroll the page- only the internship cards should scroll._
