### ISSUE TITLE
Add pagination

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#91]
### Context

We have a lot of internships that we've scraped so far and we cannot fit all of them on the same page (nor retrieve them in a single API call efficiently). We can use a concept called pagination to get a specified amount of internships (from the API). You use this everyday: going to the "next page" to get more results, jumping to certain pages (e.g. page 5 / 10), and you can set how many results per page appear (10 / 25 / 50 / 100).

Since we are using [Material](https://material.angular.io/) as our Angular UI component library, we'll use their built-in [Paginator module](https://material.angular.io/components/paginator/overview) to implement this functionality (Figure 1).

### TODO

- [ ] Add a [Paginator component](https://material.angular.io/components/paginator/overview) to the `internship-list` component
- [ ] Only show the specified number of results on each page
- [ ] When the next page button is clicked, retrieve the next load of internships via API service call 

### Notes

![paginator](https://user-images.githubusercontent.com/78290887/202807758-5b9664b4-755d-4830-bbe4-f28164b42b9d.png)

_Figure 1. "Paginator" Material UI component._

---

Remember that `getAllInternships` (will eventually) allow you to pass in a `limit` and `skip` parameter. The `limit` parameter is your results-per-page and the `skip` parameter can be calculated by the following formula:

```
skip = resultsPerPage * (pageNumber - 1)
```

For example, if you were requesting 50 internships per page and were on page 3, the `limit` parameter would be 50 and the `skip` parameter would be 100 by applying the formula:

```
skip = 50 * (3 - 1) = 100
```
