### ISSUE TITLE
Add eslint configurations

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#97]
### Context

We already have code formatting enforced for the `backend`, but let's add enforcement and precommits for the `frontend` so that we have consistency in code style and formatting. We can do this with [eslint](https://eslint.org/).

### TODO

- [x] Follow the [eslint setup](https://eslint.org/docs/latest/user-guide/getting-started) and implement it into our project
- [x] Create an eslint `precommit` hook to solve any problematic eslint violations
- [x] Fix all existing code so that it's in compliance and passes
- [x] Add this to `github-actions.yml` so that it's integrated with Actions (I see `precommit` already runs)??

**Comment by johndpjr** [comment]
Will attempt to follow a tutorial oneline: https://khalilstemmler.com/blogs/typescript/eslint-for-typescript/#:~:text=ESLint%20is%20a%20JavaScript%20linter,either%20TypeScript%20or%20JavaScript%20code.
