### ISSUE TITLE
Run background tasks on Droplet

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#99]
### Context

Our Droplet is just serving the webpage right now and not running any scraping jobs. I've looked into [Background Tasks](https://fastapi.tiangolo.com/tutorial/background-tasks/) for FastAPI, but those are light tasks and cannot be easily scheduled. Our scraping is a lot more intensive and separate from the server, so we should set up a task queue system that handles complex background tasks, like web scraping.

I've looked at and used [Celery](https://docs.celeryq.dev/en/stable/index.html) before and can attest to it's ease of use and efficiency. It is a distributed task queuing system that seems perfect for our intensive scraping jobs.

### TODO

- [ ] Integrate the Celery framework in the `backend`. You can get started with Celery [here](https://docs.celeryq.dev/en/stable/getting-started/index.html)
- [ ] Use Celery to create a background task that runs every day. This task should update all the internships (see #98)
- [ ] Update the Droplet with these changes and ensure that background tasks are running there

### Notes

You might run into issues with the Droplet running out of memory if the memory leak still isn't solved, even with the 5GB swapfile. Let us know how it goes!
